#!/bin/bash

if [[ "$*" =~ [A-Z].* ]]; then
  BIBKEY=$(echo "$*" | cut -d'@' -f2)
  echo "$BIBKEY" >> rofilog
  FILE="$BIB_NOTE_DIR/${BIBKEY:0:1}/$BIBKEY.md"
  echo "$FILE" >> ~/rofilog
  nohup i3-msg exec "alacritty -e sh -c 'sleep 0.1 && $EDITOR $FILE'" &>/dev/null &
  exit 0
fi
bibparse -s -r
