#!/usr/bin/env python
"""
Pluggable system for TaskWarrior hooks

Adapted from https://github.com/tbabej/taskpirate
by Gabriel Alcaras
"""

from tasklib import Task
from find_hooks import find_hooks

TASK = Task.from_input()

for hook in find_hooks('pirate_mod'):
    hook(TASK)

print(TASK.export_data())
