#!/bin/bash
# ########################################################################
# ROFI SCRIPT: PASS
# by Gabriel Alcaras
#
# Helper script to deal with pass through rofi
#
# ########################################################################

THEME=${1:-"dark"}

PASS=$(find ~/.password-store -type f | grep -v gaarbage | grep gpg | sed "s/\(\/home\/gaalcaras\/.password-store\/\|\.gpg\)//g" | rofi -dmenu -p " " -theme "$THEME")

if [ "$PASS" != "" ]
then
  pass show "$PASS" | head -1 | xclip -selection "clipboard" &
  notify-send -a " *******" "$PASS: pass in clipboard"
fi
