#!/bin/bash
# ########################################################################
# ROFI SCRIPT: POWER
# by Gabriel Alcaras
#
# Helper script to power down, reboot, suspend, hibernate, lock and so on.
#
# Script to be used as an extra mode for rofi (using -modi argument or the
# config file).
# ########################################################################


# -----
# SETUP
# -----
OPTIONS=$(printf "lock\\nsuspend\\nexit\\nhibernate\\nshutdown\\nreboot\\ngpu")
WM=${1:-"sway"}
THEME=${2:-"blue"}

option=$(echo -e "$OPTIONS" | rofi -dmenu -i -p power -theme "$THEME" | awk '{print $1}' | tr -d '\r\n')
if [ ${#option} -gt 0 ]
then
    case $option in
      reboot)
        systemctl reboot
        ;;
      shutdown)
        systemctl poweroff
        ;;
      exit)
        if [[ $WM == "sway" ]]; then
          swaymsg exit
        else
          i3-msg exit
        fi
        ;;
      lock)
        if [[ $WM == "sway" ]]; then
          swaylock -lef
        else
          i3lock_theme
        fi
        ;;
      suspend)
          systemctl suspend
        ;;
      hibernate)
        if [[ $WM == "sway" ]]; then
          swaylock -lef
        else
          i3lock_theme
        fi
        systemctl hibernate
        ;;
      gpu)
        optimus-manager --switch auto --no-confirm
        ;;
      *)
        ;;
    esac
  fi
