#!/bin/bash
# ########################################################################
# ROFI MODE: BLUETOOTH
# by Gabriel Alcaras
#
# Helper script to connect to bluetooth devices
#
# Script to be used as an extra mode for rofi (using -modi argument or the
# config file).
# ########################################################################


# -----
# SETUP
# -----
NEW_ZETTEL_TXT="create new zettel"
ZETTEL_DIR="$HOME/Zettelkasten/zettel"

ZETTELS=$(ls -r "$ZETTEL_DIR" --hide="*pdf")
OPTIONS=$(printf "%s\\n%s" "$NEW_ZETTEL_TXT" "$ZETTELS")
readarray -t OPTIONS_ARR <<< $"$OPTIONS"

# -----
# UTILS
# -----

# Check if string is in array
array_contains () {
  local seeking=$1; shift
  local in=1
  for element; do
      if [[ "$element" == "$seeking" ]]; then
          in=0
          break
      fi
  done
  echo $in
}

ROUND1=$(array_contains "$1" "${OPTIONS_ARR[@]}")

if [[ -z "$1" ]]; then
  # --------------------------------------
  # ROUND 0 - When you launch note in rofi
  # --------------------------------------

  printf "%s" "$OPTIONS"
elif [[ "$ROUND1" -eq 0 ]]; then
  # -------------------------------------
  # ROUND 1 - You just selected an option
  # -------------------------------------

  if [[ "$1" == "$NEW_ZETTEL_TXT" ]]; then
    echo " "
  else
    i3-msg -q "exec termite -t zettel -e 'nvim -c \"Note $1\"'"
  fi
else
  i3-msg -q "exec termite -t zettel -e 'nvim -c \"Note $1\"'"
fi
