#!/bin/bash

today_tasks=$(task rofi rc.verbose=nothing start or due:today or +OVERDUE | wc -l)
task_start=$(task rofi rc.verbose=nothing start)

function sanitize_task() {
  echo "$@" | sed -r 's/^[0-9]+ //' | sed -r 's/ \[[0-9]\] ?//'
}

msg=""
if [[ ! -z "$task_start" ]]; then
  doing=$(sanitize_task "$task_start")
  msg="$msg $doing"
fi

if [ "$today_tasks" -eq 0 ]; then
  echo "$msg"
else
  if [[ -z "$task_start" ]]; then
    task_count="$today_tasks"
  else
    task_count="(1/$today_tasks)"
  fi
  echo "$msg $task_count"
fi
