#!/usr/bin/env bash
#
# bootstrap installs things.

if [ -z ${install_sourced+x} ]; then
  echo "not sourced"
  set -e
fi

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

source $DOTFILES_ROOT/script/prepare

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    doing 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    msg 'What is your github author name?'
    read -e git_authorname
    msg 'What is your github author email?'
    read -e git_authoremail

    doing 'Setting up gitconfig'
    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

  fi
}

install_dotfiles () {
  doing 'Installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.*symlink' -not -path '*.git*')
  do
    if [[ "$src" == *".vsymlink" ]]
    then
      dst="$HOME/$(basename "${src%.*}")"
    else
      dst="$HOME/.$(basename "${src%.*}")"
    fi
    symlink "$src" "$dst" "0"
  done

  . $DOTFILES_ROOT/script/folders

  for i in ${!folders[*]}
  do
    dir=$(dirname "${folders[$i]}")
    mkdir -p "$dir"
    symlink "$i" "${folders[$i]}" "1"
  done

  for i in ${!ffiles[*]}
  do
    dir=$(dirname "${ffiles[$i]}")
    mkdir -p $dir
    symlink "$i" "${ffiles[$i]}" "0"
  done
}

setup_gitconfig
install_dotfiles

echo
msg 'Dotfiles are linked!'
read -n 1 -s -p "Press any key to continue..."
