#!/usr/bin/env bash

declare -A folders
declare -A ffiles

# NeoVim setup (from VIM)
folders[$HOME/.vim]=$HOME/.config/nvim
ffiles[$HOME/.vimrc]=$HOME/.config/nvim/init.vim

# Vim
folders[$HOME/.dotfiles/vim/ftplugin]=$HOME/.vim/after/ftplugin
ffiles[$HOME/.dotfiles/vim/dotfiles.vim]=$HOME/.vim/autoload/dotfiles.vim
ffiles[$HOME/.dotfiles/vim/myownsnips]=$HOME/.vim/myownsnips
ffiles[$HOME/.dotfiles/vim/plugin]=$HOME/.vim/after/plugin

# Mutt
folders[$HOME/.dotfiles/mutt]=$HOME/.mutt

# Vdirsyncer, khal and khard
folders[$HOME/.dotfiles/vdirsyncer]=$HOME/.vdirsyncer
ffiles[$HOME/.dotfiles/khard/khard.conf]=$HOME/.config/khard/khard.conf
ffiles[$HOME/.dotfiles/khal/config]=$HOME/.config/khal/config

# Nylas
ffiles[$HOME/.dotfiles/nylas/keymap.json]=$HOME/.nylas/keymap.json

# Ranger
ffiles[$HOME/.dotfiles/ranger/rc.conf]=$HOME/.config/ranger/rc.conf
ffiles[$HOME/.dotfiles/ranger/scope.sh]=$HOME/.config/ranger/scope.sh

# Tmuxifier
folders[$HOME/.dotfiles/tmux/layouts]=$HOME/.tmuxifier/layouts

# Systemd units (user mode)
folders[$HOME/.dotfiles/systemd]=$HOME/.config/systemd/user

# Termite
folders[$HOME/.dotfiles/termite]=$HOME/.config/termite

# Mpv
ffiles[$HOME/.dotfiles/mpv/mpv.conf]=$HOME/.config/mpv/mpv.conf
ffiles[/home/gabo/.dotfiles/mpv/input.conf]=$HOME/.config/mpv/input.conf
folders[$HOME/.dotfiles/mpv/scripts]=$HOME/.config/mpv/scripts

# Zathura
ffiles[$HOME/.dotfiles/zathura/zathurarc]=$HOME/.config/zathura/zathurarc

# Taskwarrior
ffiles[$HOME/.dotfiles/task/hooks]=$HOME/.task/hooks
