#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Install vim-plug if necessary
if [ ! -f $HOME/.vim/autoload/plug.vim ]; then
  echo '> Installing Vim-Plug...'
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim +PlugUpdate +qall
