#!/usr/bin/env bash
#
# Prepare scripts

chmod +x $DOTFILES_ROOT/script/install \
	$DOTFILES_ROOT/script/bootstrap \
	$DOTFILES_ROOT/script/functions
source "$DOTFILES_ROOT/script/functions"

usr=$(env | grep SUDO_USER | cut -d= -f 2)
home=$( getent passwd "$usr" | cut -d: -f6 )
run_as_normal="sudo -u $usr"
