#!/usr/bin/env bash
#
# Post-Install: Oh-My-Zsh, Powerline

message="Do you want to (re)install Oh-My-Zsh and Powerline theme ?"

function post_install {
  doing 'Installing Oh-My-Zsh'
  $run_as_normal git clone git://github.com/robbyrussell/oh-my-zsh.git $home/.oh-my-zsh

  doing 'Installing '
  $run_as_normal git clone https://github.com/bhilburn/powerlevel9k.git $home/.oh-my-zsh/custom/themes/powerlevel9k

  warning 'You may need to reload zsh to enact changes'
}
