#!/usr/bin/env bash
#
# Post-Install: zplug

message="Do you want to (re)install zplug?"

function post_install {
  doing 'Installing zplug'
  $run_as_normal curl -sL get.zplug.sh | $run_as_normal zsh

  warning 'You may need to reload zsh to enact changes'
}
