#!/usr/bin/env bash
#
# Post-Install: mutt

message="Do you want to set up your mutt mailboxes?"

function post_install {
  doing 'Setting up mutt'
  $run_as_normal mkdir -p $home/.cache/mutt/ehess/messages
  $run_as_normal mkdir -p $home/.cache/mutt/ehess/headers
  $run_as_normal mkdir -p $home/.cache/mutt/gmail/headers
  $run_as_normal mkdir -p $home/.cache/mutt/gmail/messages
  $run_as_normal mkdir -p $home/.cache/mutt/telecom/messages
  $run_as_normal mkdir -p $home/.cache/mutt/telecom/headers
}
