#!/usr/bin/env bash
#
# Post-install : vimplug

message="Do you want to install Vim-Plug now?"

function post_install {
  if [ ! -f $home/.vim/autoload/plug.vim ]; then
    doing 'Installing Vim-Plug'

    if [[ $response == *"ARCH"* ]]; then
      $run_as_normal pacaur -S rust cargo # This is for a plugin that uses cargo
    fi

    $run_as_normal curl -fLo $home/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  else
    warning 'Vim-Plug already installed'
  fi
}
