#!/usr/bin/env bash
#
# Post-install : vim spell check

message="Do you want to install vim spellcheck now?"

function post_install {
  if [ ! -f $home/.vim/spell/fr.utf-8.spl ]; then
    doing 'Installing Spell Checking files'
    $run_as_normal cp -R $home/.dotfiles/vim/spell $home/.vim/spell
  else
    warning 'Spell check files already there'
  fi
}
