#!/usr/bin/env bash
#
# Post-install : neovim setup

message="Do you want to setup neovim?"

function post_install {
  doing 'Symlinking from vim to neovim'
  $run_as_normal mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
  $run_as_normal ln -s ~/.vim $XDG_CONFIG_HOME/nvim
  $run_as_normal ln -s ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim
}
