#!/usr/bin/env bash
#
# Post-install : neovim setup

message="Do you want to setup neovim?"

function post_install {
  doing 'Symlinking from vim to neovim'
  mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
  ln -s ~/.vim $XDG_CONFIG_HOME/nvim
  ln -s ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim
}
