#!/usr/bin/env bash
#
# Install zsh

message="Do you want to (re)install zsh?"

function add_app {
  if [ "$system" == "arch" ]; then
    apps="$apps zsh"
  elif [ "$system" == "ubuntu" ]; then
    apps="$apps zsh"
  fi
  doing 'Adding zsh'
}
