#!/usr/bin/env bash
#
# Install termite

message="Do you want to (re)install termite?"

function add_app {
  apps="$apps termite"
  pacaur_apps="$pacaur_apps ttf-dejavu-sans-mono-powerline-git"
  doing 'Adding termite and dejavu powerline font'
}
