#!/usr/bin/env bash
#
# Install tmux

message="Do you want to (re)install tmux?"

function add_app {
  if [ "$system" == "arch" ]; then
    apps="$apps tmux"
  elif [ "$system" == "ubuntu" ]; then
    apps="$apps tmux"
  fi
  doing 'Adding tmux'
}
