#!/usr/bin/env bash
#
# Install vim 

message="Do you want to (re)install vim?"

function add_app {
  if [ "$system" == "arch" ]; then
    apps="$apps vim"
  elif [ "$system" == "ubuntu" ]; then
    apps="$apps vim"
  fi
  doing 'Adding vim'
}
