#!/usr/bin/env bash
#
# Install neovim 

message="Do you want to (re)install neovim?"

function add_app {
  if [ "$system" == "arch" ]; then
    apps="$apps neovim"
  elif [ "$system" == "ubuntu" ]; then
    apps="$apps neovim"
  fi
  doing 'Adding neovim'
}
