#!/usr/bin/env bash
#
# Install neovim 

message="Do you want to (re)install neovim?"

function add_app {
  if [ "$system" == "arch" ]; then
    apps="$apps neovim"
    doing 'Adding neovim'
  elif [ "$system" == "ubuntu" ]; then
    doing "Adding repository"
    add-apt-repository ppa:neovim-ppa/unstable
    apt-get update

    doing 'Adding neovim and python dependencies'
    apps="$apps python-dev python-pip python3-dev python3-pip neovim"
  fi
}
