#!/usr/bin/env bash
#
# Install linters and checkers

message="Do you want to (re)install linters?"

function add_app {
  if [ "$system" == "arch" ]; then
    pip_apps="$pip_apps jedi pylint shellcheck vim-vint"
    doing 'Adding various linters'
  elif [ "$system" == "ubuntu" ]; then
    doing "Adding repository"
    add-apt-repository ppa:neovim-ppa/unstable

    doing 'Adding neovim and python dependencies'
    apps="$apps python-dev python-pip python3-dev python3-pip neovim"
  fi
}
