#!/usr/bin/env bash
#
# Install neovim 

warning 'Careful! TeX packages are laaaarge'
message="Do you want to install TeX packages? (ArchLinux only)"

function add_app {
  if [ "$system" == "arch" ]; then
    apps="$apps texlive-bin texlive-bibtexextra texlive-core texlive-fontsextra"
    apps="$apps texlive-genericextra texlive-humanities texlive-latexextra"
    apps="$apps libsynctex"
    doing 'Adding TeX packages'
  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
