#!/usr/bin/env bash
#
# Install pandoc

message="Do you want to install pandoc?"

function add_app {
  if [ "$system" == "arch" ]; then
    apps="$apps pandoc"
    doing 'Adding pandoc'
  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
