#!/usr/bin/env bash
#
# Install R packages

message="Do you want to install R and RStudio?"

function add_app {
  if [ "$system" == "arch" ]; then
    pacaur_apps="$pacaur_apps r rstudio-desktop-bin"
    doing 'Adding R and RStudio'
  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
