#!/usr/bin/env bash
#
# Install neomutt

message="Do you want to install neomutt?"

function add_app {
  if [ "$system" == "arch" ]; then
    pacaur_apps="$pacaur_apps neomutt urlscan-git"
    doing 'Adding neomutt and urlscan'
  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
