#!/usr/bin/env bash
#
# Install neomutt

message="Do you want to install offlineimap?"

function add_app {
  if [ "$system" == "arch" ]; then
    pacaur_apps="$pacaur_apps offlineimap msmtp"
    doing 'Adding offlineimap'
  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
