#!/usr/bin/env bash
#
# Install pacaur on Arch

message="Do you want to install pacaur?"

function add_app {
  if [ "$system" == "arch" ]; then
    $run_as_normal mkdir -p /tmp/pacaur_install
    $run_as_normal cd /tmp/pacaur_install

    # base-devel group
    pacman -S binutils make gcc fakeroot --noconfirm --needed

    # Install pacaur dependencies from arch repos
    pacman -S expac yajl git --noconfirm --needed

    if [ ! -n "$(pacman -Qs pacaur)" ]; then
      $run_as_normal curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur
      $run_as_normal makepkg PKGBUILD --install --needed
    fi

    $run_as_normal cd $home/.dotfiles
    $run_as_normal rm -r /tmp/pacaur_install

  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
