#!/usr/bin/env bash
#
# Install pacaur on Arch

message="Do you want to install pacaur?"

function add_app {
  if [ "$system" == "arch" ]; then
    # base-devel group
    pacman -S binutils make gcc fakeroot cower --noconfirm --needed

    # Install pacaur dependencies from arch repos
    pacman -S expac yajl git --noconfirm --needed

    if [ ! -n "$(pacman -Qs pacaur)" ]; then
      $run_as_normal curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur
      $run_as_normal makepkg PKGBUILD --install --needed --clean --noconfirm

      $run_as_normal rm PKGBUILD *.tar
    fi

    
  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
