#!/usr/bin/env bash
#
# Install vdirsyncer on Arch

message="Do you want to install vdirsyncer?"

function add_app {
  if [ "$system" == "arch" ]; then
    pacaur -S vdirsyncer --needed --noconfirm
  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
