#!/usr/bin/env bash
#
# Install khal and khard

message="Do you want to install khal and khard?"

function add_app {
  if [ "$system" == "arch" ]; then
    apps="$apps python-pip"
    pip_apps="$pip_apps khal khard"
  elif [ "$system" == "ubuntu" ]; then
    apps=""
    warning 'No support for Ubuntu yet, sorry'
  fi
}
