#!/usr/bin/env bash
#
# Install ranger

message="Do you want to (re)install ranger?"

function add_app {
  apps="$apps ranger"
  pacaur_apps="$pacaur_apps subliminal"
  doing 'Adding ranger and subliminal'
}
