#!/usr/bin/env bash
#
# Install gnome firefox addon

message="Do you want to (re)install gnome firefox addon?"

function add_app {
  pacaur_apps="$pacaur_apps chrome-gnome-shell-git"
  doing 'Adding firefox gnome backend'
}
